### ISSUE TITLE
Need Readme for this project 

### ISSUE THREAD

**Issue by ausaafnabi** [ausaafnabi/Enactus-v2-refactored#7]
### Overview:
The Readme in this Repository is not updates since the advent of the project. Hence, We are planning to update this repository's Readme.
Any one interested to work can take the task.

###  Task Include : 

- [ ] Adding description with heading as Overview
- [ ] Add Badges if possible
- [ ] Section Covering information about site schema
- [ ] Contribution Section

### File to modify : 
Readme.md

### Priority : 
Urgent

### Additional Details : 
Not as such. Continue in this thread if any help is needed.
